[project]
name = "saucedemo-tests"
version = "0.1.0"
description = "Tests for saucedemo"
readme = "README.md"
requires-python = "==3.13.2"
dependencies = [
    "pytest==8.3.5",
    "ruff==0.11.10",
    "selenium==4.32.0",
    "webdriver-manager==4.0.2",
]
